#!/bin/sh
runString="powershell.exe -ExecutionPolicy RemoteSigned -Command python.exe tests.py"
exec $runString
exitCode=$?
echo "Exit-code of unittest is:"
echo $exitCode
if [ x"$exitCode" == x"0" ]
then
 exit 0
else
 echo "Not all unit-tests passed! Commit cancelled!"
 exit 1
fi